version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: scraper
      RABBITMQ_DEFAULT_PASS: scraper

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: local
    volumes:
      - ./migrations/bootstrap:/docker-entrypoint-initdb.d

  scraper-worker:
    image: teamest/scraper-worker
    volumes:
      - "./config.json:/usr/config/config.json"
    environment:
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: scraper
      RABBIT_MQ_PASS: scraper
      RABBIT_MQ_EXCHANGE: scraped_seasons
      LOG_LEVEL: info

  internal-season-api:
    image: teamest/internal-season-api
    environment:
      PORT: 9010
      MYSQL_HOST: mysql
      MYSQL_USER: internal_season
      MYSQL_PASS: internal_season
      MYSQL_DATABASE: season_data
      LOG_LEVEL: info

  season-data-worker:
    image: teamest/season-data-worker
    environment:
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: scraper
      RABBIT_MQ_PASS: scraper
      RABBIT_MQ_READ_EXCHANGE: scraped_seasons
      RABBIT_MQ_READ_QUEUE: season_data_worker__scraped_seasons
      RABBIT_MQ_WRITE_EXCHANGE: changed_season_teams
      INTERNAL_SEASON_URL: http://internal-season-api:9010
      LOG_LEVEL: info
